export const strings = {
  appName: 'CodeTemplate',
  session_logout:
    'your session has been ended because you logged in on another device',
  welcome: 'Welcome to Project Template',
  loginDescription: 'Log in to continue your quiz journey',
  emailAddress: 'Email Address',
  password: 'Password',
  forgotPassword: 'Forgot Password?',
  forgotPasswordDesc:
    'Enter the email address associated with your account. We will email a code to reset your Password.',
  submit: 'SUBMIT',
  emailLowercaseOnly: 'Email should be in lowercase letters only',
  pleaseEnterValidEmail: 'Please enter a valid email',
  pleaseEnterEmail: 'Please enter an email',
  loginCapital: 'LOG IN',
  pleaseEnterPassword: 'Please enter a password',
  confirmPasswordMinLength: 'Password must be at least 6 characters long',
  changePasswordText:
    'Your password must be more than six characters long and include a combination of letters, numbers, and special characters (e.g., !$@%#).',
  passwordCannotContainSpaces: 'Password cannot contain spaces.',
  orContinueWith: 'or continue with',
  noAccount: "Don't have an account? ",
  signUp: 'Sign Up',
  createAccount: 'Create Account',
  firstName: 'First Name',
  lastName: 'Last Name',
  userName: 'User Name',
  confirmPassword: 'Confirm Password',
  iAgree: 'I agree to the ',
  privacy_policy: 'Privacy Policy',
  privacy_policy_type: 'privacy_policy',
  and: 'and ',
  terms_conditions: 'Terms & Conditions',
  terms_and_condition_type: 'terms_and_condition',
  signUpCapital: 'SIGN UP',
  conditionsError:
    'You must accept the Terms & Conditions and Privacy Policy to proceed.',
  enterConfirmPassword: 'Please enter the confirm password',
  pleaseEnterMessage: 'Please enter an message',
  pleaseEnterSubject: 'Please enter an subject',
  pleaseEnterFullName: 'Please enter a first name',
  pleaseEnterLastName: 'Please enter a last name',
  minLengthErrFullNameError: 'First name must be at least 3 characters long',
  minLengthErrLastNameError: 'Last name must be at least 3 characters long',
  validFullNameError: 'Please enter a valid first name',
  validLastNameError: 'Please enter a valid last name',
  fullName_error: 'First name cannot start with a space',
  lastName_error: 'Last name cannot start with a space',
  nameCannotHaveMultipleSpaces: 'First name cannot have multiple spaces',
  lastNameCannotHaveMultipleSpaces: 'Last name cannot have multiple spaces',
  nameCannotEndWithSpace: 'First name cannot end with a space',
  lastNameCannotEndWithSpace: 'Last name cannot end with a space',
  enter_nickName: 'Please enter a user name',
  nickName_length: 'User name must be at least 3 characters long',
  enter_nick_name: 'Please enter a valid user name',
  lastName_cannot_start_space: 'USer name cannot start with a space',
  nickName_multiple_space: 'User name cannot have multiple spaces',
  nikeName_cannot_last_space: 'USername cannot end with a space',
  nickName_cannot_end_space: 'User name cannot end with a space',
  changeConfirmPasswordText:
    'Your password must be more than six characters long and include a combination of letters, numbers, and special characters (e.g., !$@%#).',
  confirmPasswordCannotContainSpaces: 'Password cannot contain spaces.',
  passwordsDoNotMatch: 'Passwords do not match',
  alreadyHaveAccount: 'Already have an account? ',
  login: 'Log in',
  verificationCodeLengthError: 'Verification code must be exactly 6 digits',
  verificationCodeError: 'Please enter a verification code',
  verificationCodeInvalid: 'Verification code must be a valid number',
  verifyEmail: 'Verify Your Email Address',
  codeVerification: 'Code Verification',
  codeVerificationDesc:
    'We’ve sent a 6-digit code to your email. Please enter it below to continue.',
  verificationCodePlaceholder: '6 - digit code here',
  verify: 'VERIFY',
  didNotReceiveCode: 'Didn’t receive code?',
  sendAgain: 'Send again',
  resetYourPassword: 'Reset Your Password',
  resetYourPasswordDesc:
    'Enter a new password to secure your account. Make sure it’s strong and easy to remember.',
  resetPassword: 'RESET PASSWORD',
  profile: 'Profile',
  logOut: 'Log Out',
  delete_account: 'Delete Account',
  deleteAccountConfirmation: 'Are you sure you want to delete your account?',
  delete: 'Delete',
  deleteAccountDesc:
    'This action is permanent and all your quizzes, wallet balance, and referral rewards will be lost.',
  currentlyOffline: 'You are currently offline',
  profile_images: 'profile_images',
  imageUploadFailed: 'Failed to upload image to S3',
  edit_profile: 'Edit Profile',
  changeProfileImage: 'Change Profile Image',
  enter_nickname: 'Nick Name',
  save: 'SAVE',
  logoutConfirmation: 'Are you sure you want to log out from\nQuiz Connect?',
  cancel: 'Cancel',
  logoutDesc: 'You can log back in anytime with your credentials.',
  updateRequired: 'Update Required',
  updateAvailable: 'Update Available',
  updateRequiredDesc:
    'A new version of the app is required to continue. Please update now.',
  updateAvailableDesc:
    'A new version of the app is available. Would you like to update now?',
  later: 'Later',
  updateNow: 'Update Now',
  update: 'Update',
};
